# For quick iteration/development using docker-compose
version: "3"
services:
   app:
      build: .
      ports:
         - "5000:80"
   mysql:
      build: ./db
      ports:
         - "3306:3306"
      environment:
         - MYSQL_ROOT_PASSWORD=password
