version: "3"
services:

    nginx:
      container_name: nginx
      build: ./docker/nginx
      ports:
        - 80:80
      depends_on:
        - ui
        - todo
        - aws

    mysql:
      container_name: mysql
      build: ./docker/mysql
      ports:
         - "3306:3306"
      environment:
         - MYSQL_ROOT_PASSWORD=password

    ui:
      container_name: ui
      build: ./app/ui

    todo:
      container_name: todo
      build: ./app/services/ToDoList
      depends_on:
         - mysql

    aws:
      container_name: aws
      build: ./app/services/AwsServiceCatalog
