# For quick iteration/development using docker-compose
version: "3"
services:
   app:
      build: .
      environment:
         - CONSUL_HOST=http://consul:8500
         - CONSUL_KEY=hello-web-api/master
      ports:
         - "5000:80"
   mysql:
      build: ./dev/db
      ports:
         - "3306:3306"
      environment:
         - MYSQL_ROOT_PASSWORD=password
   consul:
      image: consul:1.6.2
      ports:
         - "8500:8500" # UI
      environment:
         - CONSUL_BIND_INTERFACE=eth0
   consul-importer:
      build: ./dev/consul
      depends_on:
         - consul
