version: "3"
services:
   app:
      image: jcampos/hello-webapi
      ports:
         - "5000:80"
      deploy:
         replicas: 3
   mysql:
      image: mysql:8.0.18
      ports:
         - "3306:3306"
      environment:
         - MYSQL_ROOT_PASSWORD=password
