version: "3"
services:
   app:
      build: .
      ports:
         - "5000:80"
   mysql:
      image: mysql:8.0.18
      ports:
         - "3306:3306"
      environment:
         - MYSQL_ROOT_PASSWORD=password
