apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: nginx
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: aws-ecr
      containers:
      - name: nginx
        image: 752478895906.dkr.ecr.us-west-1.amazonaws.com/hello_webapi/nginx:latest
        ports:
        - containerPort: 80
