apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: ui
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: aws-ecr
      containers:
      - name: ui
        image: 752478895906.dkr.ecr.us-west-1.amazonaws.com/hello_webapi/ui:latest
        ports:
        - containerPort: 80
