apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file=../docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: es01
  name: es01
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  selector:
    io.kompose.service: es01
status:
  loadBalancer: {}
