apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file=../docker-compose.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: es01
  name: es01
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: es01
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: bootstrap.memory_lock
          value: "true"
        - name: cluster.initial_master_nodes
          value: es01
        - name: cluster.name
          value: es-docker-cluster
        - name: node.name
          value: es01
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
        name: es01
        ports:
        - containerPort: 9200
        resources: {}
      restartPolicy: Always
status: {}
