apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        io.kompose.service: app
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: aws-ecr
        
      containers:
      - name: app
        image: 752478895906.dkr.ecr.us-west-1.amazonaws.com/hello_webapi/app:latest
        ports:
          - containerPort: 80
        env:
        - name: CONSUL_HOST
          value: http://consul:8500
        - name: CONSUL_KEY
          value: hello-web-api/master
