apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: consul
  name: consul
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: consul

    spec:
      restartPolicy: Always
      containers:
        - name: consul
          image: consul:1.6.2
          ports:
          - containerPort: 8500
          env:
            - name: CONSUL_BIND_INTERFACE
              value: eth0
