apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: aws-ecr

      containers:
        - name: mysql
          image: 752478895906.dkr.ecr.us-west-1.amazonaws.com/hello_webapi/db:latest
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: hello_web_api
