apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
      - image: 752478895906.dkr.ecr.us-west-1.amazonaws.com/hello_webapi/ui:latest
        name: ui
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: aws-ecr
status: {}
