name 'servers'
maintainer 'Jason Campos'
maintainer_email 'jcampos8782@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures Web Servers'
version '0.1.0'
chef_version '>= 14.0'
source_url 'https://github.com/HelloWebApi/chef/servers'
